CREATE TABLE Categories 
(
Id INT PRIMARY KEY IDENTITY NOT NULL ,
CategoryName NVARCHAR(20) NOT NULL,
DailyRate INT NOT NULL,
WeekLyRate INT NOT NULL,
MonthlyRate INT NOT NULL,
WeekentRate INT NOT NULL
)

CREATE TABLE Cars 
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
PlateNumber NVARCHAR (10) NOT NULL,
Manufacturer NVARCHAR(10) NOT NULL,
Model NVARCHAR (10) NOT NULL,
CarYear INT NOT NULL CONSTRAINT CarYear CHECK ( CarYear>=1850 and CarYear<=2019) ,
CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories(Id),
Doors INT NOT NULL,
PICTURE IMAGE,
Condition NVARCHAR(4) NOT NULL CONSTRAINT Condition CHECK (Condition='Good' or Condition='Bad'),
Available NVARCHAR(3) NOT NULL CONSTRAINT Available CHECK (Available ='Yes' or Available ='No')
)

CREATE TABLE Emoloyees
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName NVARCHAR(10) NOT NULL,
LastName NVARCHAR(10) NOT NULL,
Title NVARCHAR(3) NOT NULL,
Notes TEXT
)

CREATE TABLE Customers
(

Id INT PRIMARY KEY IDENTITY NOT NULL,
DriverLicence NVARCHAR(20) NOT NULL,
FullName NVARCHAR(20) NOT NULL,
Adress NVARCHAR(20) NOT NULL,
City NVARCHAR(10) NOT NULL,
ZipCode NVARCHAR(4) NOT NULL,
Notes TEXT
)

CREATE TABLE RentalOrders
(

Id INT PRIMARY KEY IDENTITY NOT NULL,
EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Emoloyees (Id),
CustomerId int  NOT NULL FOREIGN KEY REFERENCES Customers(Id),
CarId int  NOT NULL FOREIGN KEY REFERENCES Cars(Id),
TankLevel NVARCHAR NOT NULL  CONSTRAINT Lvl CHECK (TankLevel='Empty' or TankLevel ='Full'),
KilometrageStart DECIMAL(4,2) NOT NULL,
KilometrageEnd DECIMAL(4,2) NOT NULL,
TotalKilometrage DECIMAL(4,2) NOT NULL,
StartDate DATETIME NOT NULL,
EndDate DATETIME NOT NULL, 
TotalDays INT NOT NULL,
RateApplied INT NOT NULL,
TaxRate DECIMAL (3,2) NOT NULL,
OrderStatus NVARCHAR(3) NOT NULL CONSTRAINT Status CHECK (OrderStatus ='Ready' or OrderStatus ='NotReady'),
Notes TEXT
)