CREATE TABLE Employees
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
FirstName NVARCHAR(10) NOT NULL,
LastName NVARCHAR (10) NOT NULL,
Title NVARCHAR(10) NOT NULL,
Notes TEXT
)

CREATE TABLE Custormers
(
AccountNumber INT PRIMARY KEY IDENTITY NOT NULL,
FirstName NVARCHAR(10) NOT NULL,
LastName NVARCHAR (10) NOT NULL,
TelephoneNumber DECIMAL (10,0) NOT NULL ,
EmergencyName NVARCHAR (10) NOT NULL,
EmergencyNumber DECIMal (10,0) NOT NULL ,
Notes TEXT
)

CREATE TABLE RoomStatus
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
RoomStatus NVARCHAR(5) NOT NULL CONSTRAINT RoomStat CHECK ( RoomStatus = 'Vacant' or RoomStatus = 'Taken'),
Notes TEXT
)

CREATE TABLE RoomTypes
(
RoomType INT PRIMARY KEY IDENTITY NOT NULL,
Notes TEXT
)

CREATE TABLE BedTypes
(
BedType INT PRIMARY KEY IDENTITY NOT NULL,
Notes TEXT
)

CREATE TABLE Rooms
(
RoomNumber INT PRIMARY KEY IDENTITY NOT NULL,
RoomType INT NOT NULL FOREIGN KEY REFERENCES RoomTypes(RoomType),
BedType INT NOT NULL FOREIGN KEY REFERENCES BedTypes(BedType),
Rate DECIMAL(3,2) NOT NULL,
RoomStatus  INT NULL FOREIGN KEY REFERENCES RoomStatus(Id),
Notes TEXT
)

CREATE TABLE Payments
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(Id),
PaymentDate DATETIME NOT NULL,
AccountNumber INT NOT NULL FOREIGN KEY REFERENCES  Custormers(AccountNumber),
FirstDateOcuppied DATETIME NOT NULL,
LastDateOcuppied DATETIME NOT NULL,
TotalDays INT NOT NULL,
AmoutnCharged MONEY NOT NULL,
TaxRate MONEY NOT NULL,
TaxAmount MONEY NOT NULL,
PaymentTotal MONEY NOT NULL,
Notes TEXT
)

CREATE TABLE Occupancies 
(
Id INT PRIMARY KEY IDENTITY NOT NULL,
EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(Id),
DateOccupied DATETIME NOT NULL,
AccountNumber INT NOT NULL FOREIGN KEY REFERENCES  Custormers(AccountNumber),
RoomNumber INT NOT NULL,
RateApplied DECIMAL (2,2),
PhoneCharge MONEY NOT NULL,
Notes TEXT
)

